config/routes.rb
Gallery::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'posts#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  devise_for :users, :controllers => { registrations: 'registrations',
                                       omniauth_callbacks: "users/omniauth_callbacks",
                                       sessions: 'sessions',
                                       confirmations: 'confirmations'
                                     }
  resources :posts
  resources :comments
  resources :identities, only: [:destroy]
  resources :post_events, only: [:index]
  get 'tags/:tag', to: 'posts#index', as: :tag
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :content,  presence: true, length: { maximum: 10000}
  validates :user_id,  presence: true
  validates :post_id,  presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    if user_signed_in?
      @comment = current_user.comments.build(comment_params)
      @comment.save
      post_comment = Comment.where(post_id: @comment.post.id).order('created_at DESC')
      @page = params[:comment][:page]

      if post_comment.length > 10 && @page == ''
        @page = 1
      end

      if @page != ''
        index = (@page.to_i - 1) * 10
        @comment = post_comment[index.to_i]
      end

      if post_comment.length/10 + 1 == @page.to_i
        @page = ''
      end

      respond_to do |format|
        format.html { post_path(@comment.post.id) }
        format.js
      end

    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @page = params[:page] || 1
    @comment_last = nil

    if user_signed_in? && current_user.id == @comment.user.id
      @comment.destroy
      post_comment = Comment.where(post_id: @comment.post.id).order('created_at DESC')

      if post_comment.length >= 10
        @comment_last = post_comment[(@page.to_i) * 10 - 1]
      end

      respond_to do |format|
        format.js
      end
    end

  end

  private
  def comment_params
    params.require(:comment).permit(:post_id, :content, :user_id)
  end

end

app/views/comments/_comment.html.haml
%li.comment{id: cmnt.id}
  %br
    -if cmnt.user.image.thumb.blank? || !cmnt.user.image.thumb.file.exists?
      = image_tag("avatar.png", size: "50x50", alt: "Avatar")
    -else
      = image_tag("#{cmnt.user.image_url(:thumb)}")
    .name
      = cmnt.user.username
    .time_ago
      = "#{t 'comments.lb_commented'} #{time_ago_in_words(cmnt.created_at)} #{t 'all.lb_ago'}"
      -if user_signed_in? && current_user.id == cmnt.user.id
        = link_to "delete", comment_path(id: cmnt.id, page: params[:page]), remote: true, method: :delete
    %br
      .clip
        = cmnt.content
    %br

app/views/comments/_index.html.haml
%h4 #{t 'comments.lb_comments'}
.hr_margin
  %hr
-if @comments.empty?
  .alert.alert-info
    #{t 'comments.lb_no_comments'}
%ul.comments
  - @comments.each do |cmnt|
    -cache cmnt do
      = render 'comments/comment', :cmnt => cmnt
= paginate @comments, :theme => 'twitter-bootstrap-3'
=# will_paginate @comments, renderer: BootstrapPagination::Rails

app/views/comments/_new.html.haml
.div_new_comm
  %h4 #{t 'comments.lb_what_do_you_hink'}
  .hr_margin
    %hr
  .error_area

  = form_for @post.comments.new, remote: true do |f|
    = f.hidden_field :post_id, value: @post.id
    = f.hidden_field :page, value: params[:page]
    .form-group
      = f.label :content
      %em
        (10000 #{t 'all.i_max_char'})
      %br/
      = f.text_area :content, class: "form-control", rows: "2", maxlength: "150"
      %br/
      = link_to "Back", :back
      .pull-right
        = f.submit "#{t 'comments.b_comment'}", class: "btn btn-primary"

app/views/comments/create.js.erb
<%if !@comment.nil? && @comment.errors.any? %>
    $(".error_area").html("<%= escape_javascript(render('shared/error_messages', :object => @comment)) %>")
<%else%>
    $(".comments").prepend("<%= escape_javascript(render('comments/comment', :cmnt => @comment)) %>")
    $(".error_area").html("")
    $("#comment_content").val("")
    $(".alert").remove()
    <%if @page != ''%>
        $('.comments li:last').remove()
    <%end%>
<%end%>

app/views/comments/destroy.js.erb
$('#' + <%=@comment.id%>).remove()
<%if !@comment_last.nil?%>
    $('.comments').append("<%= escape_javascript(render('comments/comment', cmnt: @comment_last))%>")
<%end%>



//if($(".comments li"))
//{
//
//}