config/routes.rb
Gallery::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'posts#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  devise_for :users, :controllers => { registrations: 'registrations',
                                       omniauth_callbacks: "users/omniauth_callbacks",
                                       sessions: 'sessions',
                                       confirmations: 'confirmations'
                                     }
  resources :posts
  resources :comments
  resources :identities, only: [:destroy]
  resources :post_events, only: [:index]
  get 'tags/:tag', to: 'posts#index', as: :tag
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy

  validates :topik,  presence: true, length: { maximum: 150}
  validates :content,  presence: true, length: { maximum: 10000}
  validates :user_id,  presence: true
  acts_as_taggable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :only_sign_in, only: [:new, :create]

  def index
    @search = Post.search("")

    if params[:tag]
      @posts = Kaminari.paginate_array(Post.tagged_with(params[:tag]).order('created_at DESC')).page(params[:page]).per(10) # Post.order('created_at DESC').page(params[:page]).per(10)
    else
      @posts = Kaminari.paginate_array(@search.result.order('created_at DESC')).page(params[:page]).per(10) #@search.result.order('created_at DESC').limit(10).page(params[:page])
      if !params[:q].nil?
        @posts = Kaminari.paginate_array(@search.result.tagged_with(params[:q][:topik_cont], :any => true).order('created_at DESC')).page(params[:page]).per(10) # @search.result.tagged_with(params[:q][:topik_cont], :any => true).order('created_at DESC').page(params[:page]).per(10)
      end
    end

    @tags = Post.tag_counts_on(:tags).most_used(20)
  end

  def show
    @post = Post.find(params[:id])
    @comments = Kaminari.paginate_array(@post.comments.order('created_at DESC')).page(params[:page]).per(10) #Comment.order('created_at DESC').page(params[:page]).per(10)
  end

  def new
    @post = Post.new
  end

  def create
    if current_user
      if params[:array_image]
        @post = current_user.posts.build(topik: "Посмотри какие изоюражения я добавил.", content: "Изображения с сайта: " + params[:array_image])
        @post.save
      else
        @post = current_user.posts.build(post_params)
        if @post.save
          @post_event = PostEvent.new(user_id: current_user.id, username: current_user.username, post_id: @post.id, post_name: @post.topik, action: "Create post")
          @post_event.save
          redirect_to root_path
        else
          @post.errors.full_messages.each do |msg|
            flash[:alert] =  msg
          end
          redirect_to new_post_path
        end
      end
    end
  end

  def edit

  end

  def destroy
    # expire_action action: 'index'
    @post = Post.find(params[:id])
    @post_event = PostEvent.new(user_id: current_user.id, username: current_user.username, post_id: @post.id, post_name: @post.topik, action: "Delete post")
    if user_signed_in? && current_user.id == @post.user.id
      if @post.destroy
        @post_event.save
        redirect_to root_path
      end
    end
  end

  private
  def post_params
    params.require(:post).permit(:topik, :content, :user_id, :tag_list)
  end

end

app/helpers/post_helper.rb
module PostHelper

  def show_content(content, post)
    truncate(content, length: 250, separator: ' ', omission: '') { link_to  ' more...',  post_path(post.id) }
  end

  def content_analysis(post)
     @img_arr = Array.new
     @text_arr = ""

     sub_img_arr = Array.new
     content_arr = post.content.split(" ")

     content_arr.each do |tmp|
       if tmp.match('https?:\/\/[\S]+')
         sub_img_arr.push(tmp)
       else
         @text_arr += " " + tmp
       end
       if sub_img_arr.length == 2 || content_arr.last == tmp
         @img_arr.push(Array.new(sub_img_arr))
         sub_img_arr.clear
       end
     end
  end
end

app/views/posts/_post.html.haml
.div_post.clip
  %br
    -if @post.user.image.thumb.blank? || !@post.user.image.thumb.file.exists?
      = image_tag("avatar.png", size: "50x50", alt: "Avatar")
    -else
      = image_tag("#{@post.user.image_url(:thumb)}", class: "img-circle")
    .name
      =  @post.user.username
    .time_ago
      = "#{t 'posts.lb_posted'} #{ time_ago_in_words( @post.created_at)} #{t 'all.lb_ago'}."
      -if user_signed_in? && current_user.id == @post.user.id
        = link_to "delete", @post, method: :delete
    %br
    %b
      = link_to  @post.topik, post_path( @post.id)
    %br
    #{t 'posts.lb_tag_list'}: #{ raw @post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')}
    %br
      - content_analysis @post
      = @text_arr
      %table
        - @img_arr.each do |img|
          %tr
            - img.each do |i|
              %td{class: "square-td-show"}
                - if img.count == 1 && @img_arr.count == 1
                  = image_tag i, class: "image_post_show_one"
                - else
                  .image_hidden
                    = image_tag i, class: "image_post_show_many"

app/views/posts/_posts.html.haml
- @posts.each do |pst|
  .div_posts.clip
    %br
    -if pst.user.image.thumb.blank? || !pst.user.image.thumb.file.exists?
      = image_tag("avatar.png", size: "50x50", alt: "Avatar")
    -else
      = image_tag("#{pst.user.image_url(:thumb)}", class: "img-circle")
    .name
      = pst.user.username
    .time_ago
      = "#{t 'posts.lb_posted'} #{ time_ago_in_words(pst.created_at) } #{t 'all.lb_ago'}."
    %br
      %b
        = link_to pst.topik, post_path(pst.id)
    - if !pst.tag_list.empty?
      %i
        #{t 'posts.lb_tag_list'}: #{ raw pst.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')}
    - content_analysis pst
    %p
      = show_content(@text_arr.to_s, pst).html_safe
    - case @img_arr.count
      - when 1
        - if @img_arr[0].count == 1
          .one-image-index
            = image_tag @img_arr[0][0], id: 'image', "data-target" => "#imageModal", "data-toggle" => "modal"
        - else
          %table{:cellspacing => "5px"}
            %tr
            - @img_arr[0].each do |img|
              %td{class: "square-td-index"}
                = image_tag img, id: 'image', "data-target" => "#imageModal", "data-toggle" => "modal"
      - when 2
        - if @img_arr[1].count == 1
          %table
            %tr
              %td{:rowspan => "2", :valign => "top", class: "td-one-size square-td-index"}
                = image_tag @img_arr[0][0], id: 'image', "data-target" => "#imageModal", "data-toggle" => "modal"
              %td{class: "td-two-size square-td-index"}
                = image_tag @img_arr[0][1], id: 'image', "data-target" => "#imageModal", "data-toggle" => "modal"
            %tr
              %td{class: "td-two-size square-td-index"}
                = image_tag @img_arr[1][0], id: 'image', "data-target" => "#imageModal", "data-toggle" => "modal"
        - else
          %table
            %tr
              %td{class: "square-td-index"}
                = image_tag @img_arr[0][0], id: 'image', "data-target" => "#imageModal", "data-toggle" => "modal"
              %td{class: "square-td-index"}
                = image_tag @img_arr[0][1], id: 'image', "data-target" => "#imageModal", "data-toggle" => "modal"
            %tr
              %td{class: "square-td-index"}
                = image_tag @img_arr[1][0], id: 'image', "data-target" => "#imageModal", "data-toggle" => "modal"
              %td{class: "square-td-index"}
                = image_tag @img_arr[1][1], id: 'image', "data-target" => "#imageModal", "data-toggle" => "modal"
      - else
        %table
          %tr
            %td{class: "square-td-index"}
              = image_tag @img_arr[0][0], id: 'image', "data-target" => "#imageModal", "data-toggle" => "modal"
            %td{class: "square-td-index"}
              = image_tag @img_arr[0][1], id: 'image', "data-target" => "#imageModal", "data-toggle" => "modal"
          %tr
            %td{class: "square-td-index"}
              = image_tag @img_arr[1][0], id: 'image', "data-target" => "#imageModal", "data-toggle" => "modal"
            %td{class: "square-td-index"}
              = image_tag @img_arr[1][1], id: 'image', "data-target" => "#imageModal", "data-toggle" => "modal"
        %br
          = link_to "Посмотреть больше картинок", post_path(pst.id), class: "col-lg-7 col-lg-offset-3 text-cente"

#imageModal.modal.fade{"aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        Привет
      .modal-body
        %img#imagepreview{:src => ""}
      .modal-footer
        Привет




-##imageModal.modal.fade{"aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
-#  .modal-dialog{:role => "document"}
-#    .modal-content
-#      .modal-header
-#        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
-#          %span{"aria-hidden" => "true"} ×
-#        %h4#exampleModalLabel.modal-title New message
-#      .modal-body
-#        %form
-#          .form-group
-#            %label.control-label{:for => "recipient-name"} Recipient:
-#            %input#recipient-name.form-control{:type => "text"}/
-#          .form-group
-#            %label.control-label{:for => "message-text"} Message:
-#            %textarea#message-text.form-control
-#      .modal-footer
-#        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
-#        %button.btn.btn-primary{:type => "button"} Send message

app/views/posts/_search_post_form.html.haml
= search_form_for @search do |f|
  .input-group
    = f.text_field :topik_cont, data: { autocomplete_source: Post.tag_counts_on(:tags).order(:name).map(&:name) }, class: "form-control", placeholder: "#{t 'posts._search_posts_form.p_search'}"
    %span.input-group-btn
      = f.submit "#{t 'posts._search_posts_form.b_search'}", class: "btn btn-primary"

app/views/posts/index.html.haml
.row
  .col-md-4
  .col-md-4
    = render 'posts/search_post_form'
    = render 'posts/posts'
    = paginate @posts, :theme => 'twitter-bootstrap-3'
    = #will_paginate renderer: BootstrapPagination::Rails
  .col-md-1
  .col-md-2
    %b
      -if !@tags.empty?
        20 #{t 'posts.index.lb_popular_tags'}
    %br
    %br
      = render 'tags/tags'

app/views/posts/new.html.haml
.row
  .col-md-3
  .col-md-6
    %h2 #{t 'posts.lb_create_post'}
    = form_for @post do |f|
      .form-group
        = f.label :topik
        %em
          (150 #{t 'all.i_max_char'})
        %br/
        = f.text_field :topik, class: "form-control", autofocus: true, maxlength: "150"
      .form-group
        = f.label :tag_list, value: "#{t 'posts.lb_tag_list'}"
        %br/
        .test
          = f.text_field :tag_list,'data-role'=>'tagsinput',class: "form-control"
      .form-group
        = f.label :content
        %em
          (10000 #{t 'all.i_max_char'})
        %br/
        = f.text_area :content, class: "form-control", rows: '7', maxlength: "10000"
        %br/
        = link_to "#{t 'all.l_back'}", :back
        .pull-right
          = f.submit "#{t 'posts.b_create_post'}", class: "btn btn-primary"

app/views/posts/show.html.haml
.row
  .col-md-3
  .col-md-6
    = render 'posts/post'
    -if user_signed_in?
      = render 'comments/new'
    = render 'comments/index'