config/routes.rb
Gallery::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'posts#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  devise_for :users, :controllers => { registrations: 'registrations',
                                       omniauth_callbacks: "users/omniauth_callbacks",
                                       sessions: 'sessions',
                                       confirmations: 'confirmations'
                                     }
  resources :posts
  resources :comments
  resources :identities, only: [:destroy]
  resources :post_events, only: [:index]
  get 'tags/:tag', to: 'posts#index', as: :tag
  

end

app/models/post_event.rb
class PostEvent < ActiveRecord::Base
end

app/controllers/post_events_controller.rb
class PostEventsController < ApplicationController
 def index
   @post_events =  Kaminari.paginate_array(PostEvent.order('created_at DESC')).page(params[:page]).per(20)  #PostEvent.paginate(:page => params[:page], :per_page => 30).order('created_at DESC')
 end
end

app/helpers/post_event_helper.rb
module PostEventHelper
    def post_exist?(id)
      begin
        post = Post.find(id)
      rescue
      end
      post.nil? ? false : true
    end
end

app/views/post_events/_post_events.html.haml
.div_posts.clip
  %table.table
    %tr
      %th
        #{t 'post_events.lb_user'}
      %th
        #{t 'post_events.lb_action'}
      %th
        #{t 'post_events.lb_post_topic'}
      %th
        #{t 'post_events.lb_date'}
    - @post_events.each do |pst_ev|
      %tr
        %td
          = pst_ev.username
        %td.min_column_width
          = pst_ev.action
        %td.column_width
          -if post_exist?(pst_ev.post_id)
            = link_to pst_ev.post_name, post_path(pst_ev.post_id)
          -else
            = pst_ev.post_name
        %td
          = pst_ev.created_at

app/views/post_events/index.html.haml
.row
  .col-md-2
  .col-md-8
    = render 'post_events/post_events'
    = paginate @post_events, :theme => 'twitter-bootstrap-3'
    = #will_paginate renderer: BootstrapPagination::Rails