config/routes.rb
Gallery::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'posts#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  devise_for :users, :controllers => { registrations: 'registrations',
                                       omniauth_callbacks: "users/omniauth_callbacks",
                                       sessions: 'sessions',
                                       confirmations: 'confirmations'
                                     }
  resources :posts
  resources :comments
  resources :identities, only: [:destroy]
  resources :post_events, only: [:index]
  get 'tags/:tag', to: 'posts#index', as: :tag
  

end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  .container-flui
    %ul.nav.navbar-nav.navbar-left
      %li
        = link_to "#{t 'layouts._header.l_brand'}", root_path
      - if user_signed_in?
        %li
          = link_to "#{t 'layouts._header.l_create_post'}", new_post_path
        %li
          = link_to "#{t 'layouts._header.l_post_events'}",  post_events_path
    %ul.nav.navbar-nav.navbar-right#bs-example-navbar-collapse-1.navbar-collapse
      %li.dropdown
        %a.dropdown-toggle{id:"dropdownMenu1", "aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :role => "button"}
          #{t 'layouts._header.lb_lang'}
          %span.caret
        %ul.dropdown-menu{'aria-labelledby'=>"dropdownMenu1"}
          %li
            = link_to "English", :locale=>'en'
          %li
            = link_to "Русский", :locale=>'ru'
      - if user_signed_in?
        %li
          = mini_avatar
        %li
          .navbar-text
            = greeting
        %li
          = link_to "#{t 'layouts._header.l_edit_profile'}", edit_user_registration_path
        %li
          = link_to("#{t 'layouts._header.l_log_out'}", destroy_user_session_path, :method => :delete)
      -else
        %li
          = link_to "#{t 'layouts._header.l_log_in'}", new_session_path(:user)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Gallery
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    .row
      .col-md-4
      .col-md-4
        = #content_tag(:div, flash[:error], :id => "flash_error") if flash[:error]
        = #content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice]
        = content_tag(:div, flash[:alert], :id => "flash_alert", :class => "alert alert-danger") if flash[:alert]
    = yield